@startuml
skinparam monochrome true
hide circle
skinparam classAttributeIconSize 0
hide footbox
skinparam BoxPadding 10
skinparam ParticipantPadding 20

box "Class FastExplorationFSM" #LightBlue
participant FSMCallback
participant callExplorationPlanner
end box

box "Class FastExplorationManager" #LightBlue
participant planExploreMotion
end box

'FSMCallback -> FSMCallback: PLAN_TRAJ state reached
note over FSMCallback
This entire lifeline is
the PLAN_TRAJ state
endnote

activate FSMCallback
FSMCallback -> FSMCallback: update position states to plan from
FSMCallback -> callExplorationPlanner: find waypoints

callExplorationPlanner -> planExploreMotion: find waypoints
activate planExploreMotion
note over planExploreMotion
Update known frontiers
Find viewpoints
Find global tour by TSP
Refine tour
endnote
'planExploreMotion -[hidden]> planExploreMotion
'planExploreMotion <-[#0000FF]-]:Here
planExploreMotion -> callExplorationPlanner: return result
deactivate planExploreMotion

alt if result = SUCCEED
    callExplorationPlanner -> callExplorationPlanner: update Bspline
end

callExplorationPlanner -> FSMCallback: return result

alt case SUCCEED
    FSMCallback -> FSMCallback: transitState(PUB_TRAJ)
else case NO_FRONTIER
    FSMCallback -> FSMCallback: transitState(FINISH)
else case FAIL
    FSMCallback -> FSMCallback: stay in PLAN_TRAJ to replan
end

@enduml
