set(_CATKIN_CURRENT_PACKAGE "octomap_test")
set(octomap_test_VERSION "0.0.0")
set(octomap_test_MAINTAINER "trung <trung@todo.todo>")
set(octomap_test_PACKAGE_FORMAT "2")
set(octomap_test_BUILD_DEPENDS "octomap" "roscpp" "rospy" "std_msgs")
set(octomap_test_BUILD_EXPORT_DEPENDS "octomap" "roscpp" "rospy" "std_msgs")
set(octomap_test_BUILDTOOL_DEPENDS "catkin")
set(octomap_test_BUILDTOOL_EXPORT_DEPENDS )
set(octomap_test_EXEC_DEPENDS "octomap" "roscpp" "rospy" "std_msgs")
set(octomap_test_RUN_DEPENDS "octomap" "roscpp" "rospy" "std_msgs")
set(octomap_test_TEST_DEPENDS )
set(octomap_test_DOC_DEPENDS )
set(octomap_test_URL_WEBSITE "")
set(octomap_test_URL_BUGTRACKER "")
set(octomap_test_URL_REPOSITORY "")
set(octomap_test_DEPRECATED "")