// Generated by gencpp from file drone_code/coord.msg
// DO NOT EDIT!


#ifndef DRONE_CODE_MESSAGE_COORD_H
#define DRONE_CODE_MESSAGE_COORD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace drone_code
{
template <class ContainerAllocator>
struct coord_
{
  typedef coord_<ContainerAllocator> Type;

  coord_()
    : ID(0)
    , frontierLocation()  {
    }
  coord_(const ContainerAllocator& _alloc)
    : ID(0)
    , frontierLocation(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _ID_type;
  _ID_type ID;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _frontierLocation_type;
  _frontierLocation_type frontierLocation;





  typedef boost::shared_ptr< ::drone_code::coord_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_code::coord_<ContainerAllocator> const> ConstPtr;

}; // struct coord_

typedef ::drone_code::coord_<std::allocator<void> > coord;

typedef boost::shared_ptr< ::drone_code::coord > coordPtr;
typedef boost::shared_ptr< ::drone_code::coord const> coordConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_code::coord_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_code::coord_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_code::coord_<ContainerAllocator1> & lhs, const ::drone_code::coord_<ContainerAllocator2> & rhs)
{
  return lhs.ID == rhs.ID &&
    lhs.frontierLocation == rhs.frontierLocation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_code::coord_<ContainerAllocator1> & lhs, const ::drone_code::coord_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_code

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone_code::coord_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_code::coord_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_code::coord_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_code::coord_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_code::coord_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_code::coord_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_code::coord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bf5c387ee16cb420675e5c5b21b2cdd";
  }

  static const char* value(const ::drone_code::coord_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bf5c387ee16cb42ULL;
  static const uint64_t static_value2 = 0x0675e5c5b21b2cddULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_code::coord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_code/coord";
  }

  static const char* value(const ::drone_code::coord_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_code::coord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 ID\n"
"geometry_msgs/PoseStamped frontierLocation\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::drone_code::coord_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_code::coord_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.frontierLocation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coord_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_code::coord_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_code::coord_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ID);
    s << indent << "frontierLocation: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.frontierLocation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_CODE_MESSAGE_COORD_H